### ISSUE TITLE
Add Zapier Integration

### ISSUE THREAD

**Issue by eugenoprea** [echoelse/elevatr-zapier#1]
https://github.com/zapier/zapier-platform-cli#getting-started

**Comment by eugenoprea** [comment]
Triggers:

- New Contact: Triggers when a new contact is added to a bucket.
- Unsubscribed Contact: Triggers when an existing contact is unsubscribed from a bucket.

Actions:

- **Add/Update Contact to Bucket(s): Add a new contact to one or multiple buckets. Can be used to update a contact's subscriptions to buckets.**
- Add Contact to an Email Series: Add a new contact to an email series. (to be added later)
- Add Bucket: Create a new bucket.
- Remove Contact from Bucket(s): Remove contact from one or multiple buckets.

These work when an email address is passed via Zapier.

**Comment by eugenoprea** [comment]
Adding some notes here:

1. When connecting Elevatr for the first time you are directed to authorize the integration, you click "Authorize" and once you do that a new tab opens which completes the authorization.

2. Then you have to go back to the tab where you started the authorization but nothing happens, so you have to refresh the zap.

Is there any way to be automatically redirected to the tab where you started from?

**Comment by relu** [comment]
I'm working on this in echoelse/elevatr-web#487

**Comment by relu** [comment]
Oh, wait... I think you're referring to something else. I'm pretty sure you can't really redirect to an existing tab like that. This is something Zapier needs to address.

**Comment by eugenoprea** [comment]
I will test other apps to see how they handle this and come back with details.
